name: Build Unity Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Unity
        uses: game-ci/unity-actions/setup@v2
        with:
          unityVersion: 2022.3.0f1

      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: Android

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
